import type { Metadata } from 'next'
import './globals.css'
import { TranslationProvider } from '@/context/TranslationContext'

export const metadata: Metadata = {
	title: 'Suhbatchi - AI coll center',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<TranslationProvider>{children}</TranslationProvider>
			</body>
		</html>
	)
}
